version: '2'
services:
  php:
    image: oliverlundquist/multiarch:0.0.4
    build:
      dockerfile: docker/build/multiarch
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm/v7
          - linux/arm64/v8
          - linux/arm/v6
